n<-as.integer(readline(prompt = "Enter the no. of students: "))
USN<-vector(mode ="character",length = n)
Name<-vector(mode = "character",length = n)
Marks<-vector(mode = "numeric",length = n)
for(i in 1:n){
print("Enter USN")
  USN[i]<-as.character(readline())
print("Enter Name")
  Name[i]<-readline()
print("Enter Marks")
  Marks[i]<-as.integer(readline())
Student<-data.frame(USN,Name,Marks)
}
print("The details are as follows")
print(Student)
Age<-vector(mode = "integer",length = n)
for(i in 1:n)
print("Enter Age")
  Age[i]<-as.integer(readline())
Student<-cbind(Student,Age)
print(Student)
for(i in 1:n)
  if(Student[i, ][3] > 25)
    if(Student[i, ][4] > 20)
      print(Student[i, ])
