n<-as.integer(readline(prompt = "Enter the no. of emp:"))
empid<-vector(mode = "integer",length = n)
empname<-vector(mode = "character",length = n)
doj<-vector(mode = "character",length = n)
empcode<-vector(mode = "integer",length = n)
dept<-vector(mode = "character",length = n)
desi<-vector(mode = "character",length = n)
for(i in 1:n){
print("Enter the empid:")
  empid[i]<-as.integer(readline())
print("Enter the empname:")
  empname[i]<-as.character(readline())
print("Enter the doj:")
  doj[i]<-as.character.Date(readline())
print("Enter the empcode:")
  empcode[i]<-as.integer(readline())
print("Enter the dept:")
  dept[i]<-as.character(readline())
print("Enter the designation:")
  desi[i]<-as.character(readline())
empl<-data.frame(empid,empname,doj,empcode,dept,desi)
}
print("The details are as follows for csv:")
print(empl)
write.csv(empl,"/home/student/Documents/pas/emp.csv")
readempl<-read.csv("/home/student/Documents/pas/emp.csv")
print(readempl)
print("The details are as follows for csv2:")
print(empl)
write.csv2(empl,"/home/student/Documents/pas/emp.csv2")
readempl2<-read.csv2("/home/student/Documents/pas/emp.csv2")
print(readempl2)
print("Enter a new row:")
l<-readline(prompt = "empid: ")
m<-readline(prompt = "empname: ")
n<-readline(prompt = "doj: ")
o<-readline(prompt = "empcode: ")
p<-readline(prompt = "dept: ")
q<-readline(prompt = "desi: ")
x<-data.frame(l,m,n,o,p,q)
write.table(x,"/home/student/Documents/pas/emp.csv",col.names = F,append = T,row.names = T,quote = F,sep = ',')