x<-data.frame(airquality)
dim(x)
sapply(x,class)
print("The missing values are as follows: ")
xcolnames<-colnames(x)
sx<-colSums(is.na(x))
print(sx)
for(i in 1:4)
y[,i]<-ifelse(is.na(x[,i]),mean(x[,i],na.rm=T),x[,i])
print(y)
z<-na.omit(x)
print(z)
